window.PROFILE_CONFIG = {
      "p_36acfa09": {"label": "Vancouver, British Columbia", "brand": "ProServ Restoration", "city": "Vancouver", "state": "British Columbia", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/t2ESS23SNZze5H7H9"},
      "p_d97298ff": {"label": "Edmonton, Alberta", "brand": "All Pro Restoration", "city": "Edmonton", "state": "Alberta", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/9dG6W6YwXTJCqLqz7"},
      "p_7267e0af": {"label": "Toronto, Ontario", "brand": "Quick Response Restoration", "city": "Toronto", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/cjSExwpwuFxWkJkg9"},
      "p_ab2cad63": {"label": "Winnipeg, Manitoba", "brand": "Tree City Restoration", "city": "Winnipeg", "state": "Manitoba", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/ykZAiA4MaRqyKfLk9"},
      "p_63b67f3c": {"label": "London, Ontario", "brand": "Forest City Restoration", "city": "London", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/R5c1CyemBbRTKK2t5"},
      "p_52a9afea": {"label": "Montréal, Quebec", "brand": "MTL Restoration", "city": "Montréal", "state": "Quebec", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/4rz2AJuSirbtsvVN7"},
      "p_abd0f4d7": {"label": "Barrie, Ontario", "brand": "RestoXperts", "city": "Barrie", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/kPjt8xbFcnQkyk948"},
      "p_c5868f58": {"label": "Waterloo, Ontario", "brand": "Clean State Restoration", "city": "Waterloo", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/NPCXPUUNPvP3ynkC6"},
      "p_90f23667": {"label": "Mississauga, Ontario", "brand": "All Clear Recovery", "city": "Mississauga", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/vmP4MVnJaVsyApFB6"},
      "p_57687b96": {"label": "Vaughan, Ontario", "brand": "Rapid Restore Ontario", "city": "Vaughan", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/LCJHVRBQhfpXzm4e8"},
      "p_eeaa34bc": {"label": "Ottawa, Ontario", "brand": "Maximum Restore Solutions", "city": "Ottawa", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/w83Pz6X9325vQkxc7"},
      "p_bf53b732": {"label": "Oshawa, Ontario", "brand": "Fast Response Restoration", "city": "Oshawa", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/gahgmB6bfRsv4sqo7"},
      "p_c5d576b7": {"label": "Richmond Hill, Ontario", "brand": "Prime Response", "city": "Richmond Hill", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/X7yAn1sDuVpAuuug8"},
      "p_09c7c1c4": {"label": "Vaughan, Ontario", "brand": "Blue Line Recovery", "city": "Vaughan", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/6jcwrYfSd9QuzYXq6"},
      "p_72a0915c": {"label": "Aurora, Ontario", "brand": "First Guard Restoration", "city": "Aurora", "state": "Ontario", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/TGSKgGfTLx6WJH6w6"},
      "p_da83f2c4": {"label": "North York, Canada", "brand": "Circle Restoration Group", "city": "North York", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/izEtjPBeSK4ahHPy6"},
      "p_4070ac47": {"label": "Brampton, Canada", "brand": "Greg & Sons Restoration", "city": "Brampton", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/uqJkrjo1a9qjRTsL9"},
      "p_650e28e6": {"label": "Toronto, Canada", "brand": "Dry Kings Toronto", "city": "Toronto", "country": "Canada", "reviewUrl": "https://share.google/8xMfKJtxKdStR7TNY"},
      "p_bf2c32bb": {"label": "Edmonton, Canada", "brand": "Quick Restoration", "city": "Edmonton", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/wcSJtFRCA8cj5tok8"},
      "p_c4983bc5": {"label": "Calgary, Canada", "brand": "Clean Response Mitigation", "city": "Calgary", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/TKbq1jayxBTfPgK28"},
      "p_ec08c6e1": {"label": "Calgary, Canada", "brand": "Best Restoration", "city": "Calgary", "country": "Canada", "reviewUrl": "https://share.google/NkUHWWa7um7uwKMmx"},
      "p_ebd81abc": {"label": "Winnipeg, Canada", "brand": "Super Restoration", "city": "Winnipeg", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/EDUbRDqEvWMTVLBy8"},
      "p_24722366": {"label": "Kitchener, Canada", "brand": "KWC Recovery Group", "city": "Kitchener", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/yySW6Bx9T5erkToj8"},
      "p_e7769b89": {"label": "St Catherines, Canada", "brand": "Advanced Water Recovery", "city": "St Catherines", "country": "Canada", "reviewUrl": "https://share.google/EOS6eMiiT00cXYlwz"},
      "p_019ff94c": {"label": "Markham, Canada", "brand": "Priority Recovery", "city": "Markham", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/LAt8qH4QCHwyUv7m6"},
      "p_fe2dbf46": {"label": "Oshawa, Canada", "brand": "Precision Mitigation", "city": "Oshawa", "country": "Canada", "reviewUrl": "https://share.google/LngAF7ZtB5l4ecQuf"},
      "p_b0a3a9bc": {"label": "Bradford, Canada", "brand": "HydraTech Dry Team", "city": "Bradford", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/2w3HCUU425qDnxs69"},
      "p_26fce8ad": {"label": "Whitby, Canada", "brand": "Top Team Restoration", "city": "Whitby", "country": "Canada", "reviewUrl": "https://share.google/GMj395HT8q0DbUvFU"},
      "p_6d8f4977": {"label": "Orillia, Canada", "brand": "EAS Restoration", "city": "Orillia", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/eYkLgPnK4jLcc9ADA"},
      "p_3c0be003": {"label": "Burlington, Canada", "brand": "Trevors Restoration Team", "city": "Burlington", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/p8x8WSdidAUnx1ak7"},
      "p_5b97770a": {"label": "North Vancouver, Canada", "brand": "Care Restoration", "city": "North Vancouver", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/RKgVr6V7eNKKRVhz6"},
      "p_160911bd": {"label": "Etobicoke, Canada", "brand": "RTT Restoration", "city": "Etobicoke", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/gbTb8cgL3wq19T8a6"},
      "p_158e09bb": {"label": "Toronto, Canada", "brand": "Super Restoration", "city": "Toronto", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/e95vykdWErwxzPL77"},
      "p_64c15e85": {"label": "Peterborough, Canada", "brand": "Fast Dry Restoration", "city": "Peterborough", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/a1tT8G8Ek3cf32yg8"},
      "p_97a03a76": {"label": "Cambridge, Canada", "brand": "Family Restoration", "city": "Cambridge", "country": "Canada", "reviewUrl": "https://share.google/VvK34Vsr3PWyQOCGU"},
      "p_966766c5": {"label": "Mississauga, Canada", "brand": "Trust Restoration", "city": "Mississauga", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/sU52ZmjSPF7f4Ess8"},
      "p_9fa79c37": {"label": "Toronto, Canada", "brand": "Dependable Restoration", "city": "Toronto", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/4sdq9Rfu6rhLy9Hz7"},
      "p_a00b4ac7": {"label": "Toronto, Canada", "brand": "Reliable Property Recovery", "city": "Toronto", "country": "Canada", "reviewUrl": "https://maps.app.goo.gl/bR47B1Km4QMAestD6"},
      "p_571d95c3": {"label": "Cincinnati, USA", "brand": "Dry Guard Solutions", "city": "Cincinnati", "country": "USA", "reviewUrl": "https://maps.app.goo.gl/UqmFuSAszxobQHYX9"},
      "p_e928a3dd": {"label": "Rochester, USA", "brand": "Fresh Start Restoration", "city": "Rochester", "country": "USA", "reviewUrl": "https://maps.app.goo.gl/sbjBJTSnRnxoTFkx6"},
      "p_38697fff": {"label": "Albany, USA", "brand": "Comfort Restoration", "city": "Albany", "country": "USA", "reviewUrl": "https://maps.app.goo.gl/creLbgVe9s7MUmxq5"},
      "p_ac3be212": {"label": "Providence, USA", "brand": "Reliable Restoration", "city": "Providence", "country": "USA", "reviewUrl": "https://maps.app.goo.gl/Qp5JQ8sMRAktjDAR6"},
      "p_56c5ed21": {"label": "Syracuse, USA", "brand": "Pure Clean Restoration", "city": "Syracuse", "country": "USA", "reviewUrl": "https://maps.app.goo.gl/hQbG24dDFiTFhjvv6"},
      "p_47bf1bfb": {"label": "Northolt, UK", "brand": "Ironclad Restoration", "city": "Northolt", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/4yTbYBn9ctvM48sv7"},
      "p_bb0635bc": {"label": "London, UK", "brand": "Apex Property Recovery", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/eMyfU13zGg1hxYj67"},
      "p_ee4d4202": {"label": "Thornton Heath, UK", "brand": "24/7 Property Rescue", "city": "Thornton Heath", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/ZQbiCrt5G1ka3jHX9"},
      "p_5d9b3640": {"label": "London, UK", "brand": "PureGuard Restorations", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/UKiUAUt5gdSECKVHA"},
      "p_34a7190f": {"label": "Morden, UK", "brand": "RenewalPro Services", "city": "Morden", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/YxTskhhFi56wFyZ18"},
      "p_fd358775": {"label": "London, UK", "brand": "ClearPath Property Recovery", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/bgzYVKH8uhiAgv9k7"},
      "p_bf1413b9": {"label": "London, UK", "brand": "FreshStart Mitigation", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/Y9eRMEia5KwUMYNn8"},
      "p_8d28979a": {"label": "London, UK", "brand": "Brightside Restoration Co.", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/ea4FQUQkfWrk8dzs7"},
      "p_299d80de": {"label": "London, UK", "brand": "Evergreen Recovery Group", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/SF3fZDPTRUgnzviQ8"},
      "p_ce32b9ad": {"label": "London, UK", "brand": "A1 Restoration Services", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/14tCEtL7fRorGspZ9"},
      "p_e97e5b7e": {"label": "London, UK", "brand": "SafeHaven Property Rescue", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/9pcdQvE382Eek9766"},
      "p_60a0649b": {"label": "London, UK", "brand": "Shield Restoration", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/N5PJjkBwEeXVK8yi9"},
      "p_f4af550d": {"label": "London, UK", "brand": "Precision Restoration Partners", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/pWufYmsRv7A5sf8t5"},
      "p_a1e7f727": {"label": "London, UK", "brand": "Integrity Mitigation Co.", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/CQKDZghLUg2Y6jMMA"},
      "p_bc8e8246": {"label": "London, UK", "brand": "Benchmark Restoration Group", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/Y1kpeF4UG5q68JeJ8"},
      "p_9939ec77": {"label": "London, UK", "brand": "Phoenix Property Recovery", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/GwJBcAYzhnB44E9X9"},
      "p_76b41388": {"label": "London, UK", "brand": "Resilience Restoration", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/uCDqdjNZXuxFN9Fz9"},
      "p_253e7761": {"label": "London, UK", "brand": "Core Restoration", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/PAuKykFvf1YFYrxm6"},
      "p_733b773c": {"label": "London, UK", "brand": "Guardian Restoration Services", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/m2KVrbpAqp8svUEk8"},
      "p_174411cc": {"label": "London, UK", "brand": "TotalShield Property Recovery", "city": "London", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/5YskrxX7BTevYrnv9"},
      "p_9f565b52": {"label": "Birmingham, UK", "brand": "A1 Pro Restoration Group", "city": "Birmingham", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/qsw4MQsR4KJf248w8"},
      "p_211134ed": {"label": "Manchester, UK", "brand": "National Mitigation Services", "city": "Manchester", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/NLKajBLBoxmBAY246"},
      "p_f8228fae": {"label": "Glasgow, UK", "brand": "All Phase Restoration", "city": "Glasgow", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/XNBVe1JPHTxtPrDj8"},
      "p_3fca0a9b": {"label": "Sheffield, UK", "brand": "Rapid Restoration", "city": "Sheffield", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/VrVYF7tPczBMEPnS6"},
      "p_5bdd8281": {"label": "Edinburgh, UK", "brand": "Resto Experts", "city": "Edinburgh", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/JuUMMC6FjDMe34xk6"},
      "p_f5238e68": {"label": "Leicester, UK", "brand": "Pinnacle Restoration", "city": "Leicester", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/xhfDicVsYswCz29v6"},
      "p_728de6db": {"label": "Leeds, UK", "brand": "All Pro Restoration", "city": "Leeds", "country": "UK", "reviewUrl": "https://maps.app.goo.gl/Ap9DSJRUnzxiWYss5"},
};
